version: "3.9"

services:
  web:
    build:
      context: ..
      dockerfile: Docker_Image/Dockerfile
    ports:
      - "5001:5000"
    environment:
      - PYTHONPATH=.
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=melvis123
      - POSTGRES_DB=hospital
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - FLASK_ENV=development
      - SECRET_KEY=b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZWQyNTUxOQAAACBIuQNrZ8/MqLGjk1JMx8CW2s0itbKJMQYlNxvfgAaO5QAAALDv/IlC7/yJQgAAAAtzc2gtZWQyNTUxOQAAACBIuQNrZ8/MqLGjk1JMx8CW2s0itbKJMQYlNxvfgAaO5QAAAEB9WPK5UfqOdQx+yGstOQCd1gSFIdDXMoj20CX7TOwU9Ei5A2tnz8yosaOTUkzHwJbazSK1sokxBiU3G9+ABo7lAAAAJm1lbHZpcy1kZXZAbWVsdmlzLWRldi1IUC1FTlZZLU5vdG
    depends_on:
      - db
    volumes:
      - ../Code_Source:/app/Code_Source

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: melvis123
      POSTGRES_DB: hospital
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
